### ISSUE TITLE
Meta cnb releases do not print out dependencies

### ISSUE THREAD

**Issue by arjun024** [paketo-buildpacks/github-config#101]
With the change from tgz to buildpackages for referencing implementation cnbs from meta cnbs,
meta cnb draft releases do not print list of dependencies anymore.

See:
https://github.com/paketo-buildpacks/nodejs/releases/tag/untagged-4acc022b4b2bc34b8fca
https://github.com/paketo-community/python/releases/tag/untagged-44e0b4d6c3a9d287d1e7

**Comment by ryanmoran** [comment]
This has been addressed by adding buildpackage support to `jam summarize` in https://github.com/paketo-buildpacks/packit/releases/tag/v0.2.2. We will need to update the version of `jam` used in our workflows to support this new functionality.

**Comment by ryanmoran** [comment]
This is resolved by https://github.com/paketo-buildpacks/github-config/pull/104.
