### ISSUE TITLE
Inaccessible integration tests - asks for $GIT_TOKEN

### ISSUE THREAD

**Issue by arjun024** [paketo-buildpacks/github-config#155]
When I try to run integration tests using `./scripts/integration.sh` on any buildpack (`go-dist` logs shown here), it fails with with the following error:

```
Fetching GIT_TOKEN
<path-to-buildpack>/scripts/.util/git.sh: line 18: lpass: command not found

...

    init_test.go:71:
        Unexpected error:
            <*errors.errorString | 0xc0004f2010>: {
                s: "unexpected response status: 401 Unauthorized",
            }
            unexpected response status: 401 Unauthorized
        occurred
```

Then, I figure out and install `lpass` cli, it hits a different error:

```
Fetching GIT_TOKEN
Error: Could not find decryption key. Perhaps you need to login with `lpass login`.

...
    init_test.go:71:
        Unexpected error:
            <*errors.errorString | 0xc0004f2010>: {
                s: "unexpected response status: 401 Unauthorized",
            }
            unexpected response status: 401 Unauthorized
        occurred
```

The error points to [go-dist init_test.go#L71](https://github.com/paketo-buildpacks/go-dist/blob/477308b2af12e783fc166e0db1baea166c8dafed/integration/init_test.go#L71) where [occam's BuildpackStore/Freezer](https://github.com/paketo-buildpacks/occam/blob/a0f4e61fd2b2ae1beb0b16619c5dacae66cdfda0/buildpack_store.go#L38-L40) seems to expect `$GIT_TOKEN` variable to set to a valid github token.

It looks like if I get access to the following lastpass directory, the issue is solved.
https://github.com/paketo-buildpacks/github-config/blob/2fe8f569e4fb55856174cfc77e2e7535a957aa8f/implementation/scripts/.util/git.sh#L14

---

**Problem**: These tests are not accessible to the community

**Proposal**: Either make loading `GIT_TOKEN` optional, or error out the test and force users to pass/load their own github token (not the nicest idea)

**Comment by sophiewigmore** [comment]
Resolved in https://github.com/paketo-buildpacks/github-config/pull/212
