### ISSUE TITLE
jam update buildpack action uses out of date jam version

### ISSUE THREAD

**Issue by fg-j** [paketo-buildpacks/github-config#277]
Currently, the update buildpack action [uses jam 0.9.0](https://github.com/paketo-buildpacks/github-config/blob/9dd14aebf9d2ce3019e6208271363c915c3daf2d/actions/buildpack/update/action.yml#L16). However, the latest is v0.11.0. The update includes [a fix](https://github.com/paketo-buildpacks/packit/pull/154) introduce in 0.10.1 that enables `jam update builder` to work when registry path != buildpackage ID. 

There's an issue with that fix when used with private registries (see https://github.com/paketo-buildpacks/packit/issues/175), so it might not make sense to upgrade the version yet, but it would be good to have a mechanism that keeps this jam version up to date.

**Comment by sophiewigmore** [comment]
Note that there exists [an update-tools workflow](https://github.com/paketo-buildpacks/github-config/blob/main/.github/workflows/update-tools.yml) that could possibly be used to keep the jam version in the actions up to date if we add a `tools.json` file like we have for the builder, implementation, and language family sub directories.

**Comment by sophiewigmore** [comment]
Update: the issue @fg-j mentioned (https://github.com/paketo-buildpacks/packit/issues/175) has been resolved and the fix is available in packit v0.11.1
