### ISSUE TITLE
Make dependency update PR names more informative

### ISSUE THREAD

**Issue by fg-j** [paketo-buildpacks/github-config#329]
Automated PRs generated by concourse pipelines to update dependencies have names like: "Updating version for dotnet-runtime for 3.1.X". This is handy because it's easy to determine, at a glance, what the PR is changing. (Like if you're looking at the changelog on a draft release to determine the correct semver version for the next one).

PRs opened by the update dependencies workflow are [all named the same thing](https://github.com/paketo-buildpacks/github-config/blob/7f0e3f54cb4a363378e50de74cb7b1cf70e6bcc4/implementation/.github/workflows/update-dependencies.yml#L29)

It would be helpful if these PRs could somehow give a hint about the changes they made.

**Comment by fg-j** [comment]
This might entail that the dependency updating action needs to output some information about the diff between the old and new `buildpack.toml`. 

Notably, this would also be helpful if we want to auto-label PRs based on whether they add a patch/minor/major change.

**Comment by sophiewigmore** [comment]
This will also be helpful for https://github.com/paketo-buildpacks/dotnet-core-sdk/issues/223 in creating automation to update the compatibility table, since that automation will need to be aware of the versions updated in order to make the appropriate compatibility changes.
