### ISSUE TITLE
Fix auto-merge PR to run after labels are added

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-buildpacks/github-config#451]
Since the introduction of the `Set  Validate PR Labels` [workflow](https://github.com/paketo-buildpacks/github-config/blob/main/implementation/.github/workflows/label-pr.yml), the auto-merge workflow step often fails to merge in cases when it should because it runs before the labels are added, and the PR is in a "blocked" state. It's not a huge problem, but maintainers then have to perform a manual step to merge the PR. This is the whole reason that the auto-merge functionality exists, so we should make sure it works.

We should determine a clean way to ensure that the [auto merge workflow](https://github.com/paketo-buildpacks/github-config/blob/main/implementation/.github/workflows/auto-merge.yml) re-runs when labels are added, or waits to run until the PR review is submitted as well as labels being added.

**Comment by sophiewigmore** [comment]
I investigated this a bit, but the issue lies in the fact we only want to run the auto-merge step in the case that the auto-approve workflow succeeds (current behaviour). If we modify the auto-merge workflow triggers to include labeling, it will always run even when the auto-approve workflow hasn't run which is a waste of resources. Github does not have a nice way of `AND`ing together triggers.

**Comment by sophiewigmore** [comment]
@fg-j is currently testing [a solution](https://github.com/paketo-buildpacks/occam/pull/134) in occam, jam, and packit. Upon seeing expected behaviour consistently in those places, we can consider adding this to our other repositories and closing this out.

**Comment by fg-j** [comment]
Here's an example of the auto-merge in action on packit: https://github.com/paketo-buildpacks/packit/pull/326. The PR opened, was approved, auto-squash enabled. I intervened to add a semver label, then the branch automatically merged once all checks went green.

**Comment by sophiewigmore** [comment]
I'd like to see this rolled out to our other repos. @paketo-buildpacks/tooling-maintainers can we get a 👍 or 👎 on that?
