### ISSUE TITLE
Add automation to file issues on workflow failures

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-buildpacks/github-config#459]
## Context
Recently, we added [automation to our stack release repositorie](https://github.com/paketo-buildpacks/full-stack-release/commit/7915b6da45f3cc04944f6a5f246d0faabfe33597)s to file an issue and tag maintainers if the release workflow fails.

We added this because our automation fails silently, and it's easy to miss unless you look at the workflows.

## Issue
We should consider adding a similar mechanism for our buildpack release workflows so that we're made aware of failures as they happen, rather than days to weeks later when we go to cut a release. It may also be helpful to implement this automation step for the `push buildpackage` workflows as well.

## Outcome
A workflow step that will file an issue on release/buildpackage push failures for our buildpacks.

**Comment by fg-j** [comment]
This would be especially useful for the builders repos, where the release and push steps are fully automated.
