### ISSUE TITLE
Multiple draft releases created

### ISSUE THREAD

**Issue by ForestEckhardt** [paketo-buildpacks/github-config#46]
**Context**
When two or more PRs are merged into a meta buildpack close together there is a time in which the previous draft release is deleted by one of the merging PRs and when the later of the PRs see that there is no draft release so they create a draft release that is the same version as the other PR resulting in two or more draft releases of a the same version.

**Proposal**
Figure out a way to set up the action such that it is either impossible to merge several PRs in rapid succession or make the action smart enough to wait for the draft that is building.

**Outcome**
It is impossible to end up in a situation where there are multiple draft releases for the same version on a metabuildpack.

**Comment by ryanmoran** [comment]
I think we reset the draft at the very top of the workflow. It may make more sense to reset it right before we create the release so that the window where we might create multiple drafts at once is minimal.

**Comment by ryanmoran** [comment]
@ForestEckhardt We've made a bunch of changes to the release creation workflow. Are we still seeing this these days?

**Comment by ForestEckhardt** [comment]
I have not seen this recently. I will close and reopen it I see this again.
