### ISSUE TITLE
Create-draft-release workflow fails to upload assets in some cases

### ISSUE THREAD

**Issue by thitch97** [paketo-buildpacks/github-config#463]
## What happened?

* What were you attempting to do?

Create a draft release of a buildpack.

* What did you expect to happen?

Upon merging a pull request, the `create-draft-release` workflow runs successfully resulting in a draft release of the buildpack with packaged buildpack artifacts attached as release assets. 

* What was the actual behavior? Please provide log output, if possible.

The release job failed to upload the buildpack artifacts ([example 1](https://github.com/paketo-buildpacks/pip-install/runs/6192645138?check_suite_focus=true#step:14:79) & [example 2](https://github.com/paketo-buildpacks/php/runs/6259907795?check_suite_focus=true#step:13:679)).

## Checklist

* [ ] I have included log output.
* [ ] The log output includes an error message.
* [ ] I have included steps for reproduction.

**Comment by fg-j** [comment]
I've seen this a lot for .NET Core and Golang buildpack releases as well. Both language family and component buildpacks.

**Comment by ryanmoran** [comment]
@thitch97 @fg-j we've made some improvements to this workflow recently. Do we feel that this has been resolved sufficiently?

**Comment by fg-j** [comment]
Yeah, the release workflow is much less flakey now.

**Comment by robdimsdale** [comment]
Closing as this appears to have been resolved
