### ISSUE TITLE
Package script errors out when no git tags and no version provided

### ISSUE THREAD

**Issue by arjun024** [paketo-buildpacks/github-config#48]
`./script/package.sh` fails with `fatal: No names found, cannot describe anything.`

See
https://github.com/paketo-buildpacks/github-config/blob/766fad169908cc3cf1829ca1754c9b152789c668/implementation/scripts/package.sh#L58

**Comment by ryanmoran** [comment]
There is a similar issue in the language-family release workflow as can be seen here: https://github.com/paketo-community/ruby/runs/717212100?check_suite_focus=true#step:7:1
