### ISSUE TITLE
Add support for library repositories

### ISSUE THREAD

**Issue by robdimsdale** [paketo-buildpacks/github-config#502]
## Describe the Enhancement

Currently we support a few types of repositories:
* language family buildpacks
* component buildpacks
* stacks
* builders

We have started to identify areas where we would benefit from libraries (e.g. https://github.com/paketo-buildpacks/libreload-packit) and as such it would be valuable to be able to manage shared configuration from this common repository.

## Possible Solution

I'm not 100% sure yet what types of configuration we would want, but I'd expect we would some of the following:
* PR checks (tests, linter, etc)
* post-merge tests and draft release
* automatic semantic versioning 

I'd imagine a lot of this would look like what we already have in [`packit`](https://github.com/paketo-buildpacks/packit/tree/v2/.github) - in fact we should consider that `packit` could consume this newly-added library section, too.

## Motivation
Manually creating github configuration and scripts for libraries is brittle and error-prone. Locating them in a common place has proven valuable for other types of repositories.

**Comment by joshuatcasey** [comment]
+1 to the idea that `packit` could use this templated workflow

**Comment by robdimsdale** [comment]
We have started to implement this with #542 and #556, and the new `libdependency` work will continue to drive out shared config for a library. We can close this issue now.
