### ISSUE TITLE
Can no longer run stacks `./scripts/create.sh` locally

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/github-config#576]
## Expected Behavior

It should create a stack when passed no arguments.

## Current Behavior

I get the following error message:
```shell
 ‣ ./scripts/create.sh
Using jam 1.2.3
./scripts/create.sh: line 82: @: unbound variable
```

## Possible Solution

Appears that the `secrets` variable needs to be handled in the case that there are no secrets to pass. I'm too lazy to figure that part out and will just run `jam create-stack` directly.

## Steps to Reproduce

1. Checkout any of the stack repos
2. Run `./scripts/create.sh`

## Motivations

I used to just run this helpful script and now I have to type a longer command to get the same outcome.

**Comment by robdimsdale** [comment]
@ryanmoran odd. This works locally for me on both osx and linux (Ubuntu Jammy).

What version of `bash` are you running?

**Comment by robdimsdale** [comment]
Yup, when I switch the version of bash that comes installed with OSX I get the same error:

```
❯ /usr/bin/env bash --version
GNU bash, version 5.1.16(1)-release (aarch64-apple-darwin21.1.0)

❯ /bin/bash --version
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin21)
Copyright (C) 2007 Free Software Foundation, Inc.

[ replace `/usr/bin/env bash` with `/bin/bash` in script ]

❯ ./scripts/create.sh
Using jam 1.4.1
/Users/rdimsdale/workspace/paketo-buildpacks/jammy-tiny-stack/scripts/create.sh: line 82: @: unbound variable
```

Do you think it's reasonable for consumers to use a newer version of bash (e.g. `brew install bash`)? Bash v4 (which I think is the minimum required version) has been out since 2011.

If you agree, we can document this requirement.
