### ISSUE TITLE
There should be a mechanism to propagate config files to implementation/meta cnb repos

### ISSUE THREAD

**Issue by arjun024** [paketo-buildpacks/github-config#6]
Here's a proposal:

This is how the structure of the repository should be:

```
├── .github
│   ├── (the github action workflow for this repo that sends dispatch to target repos)
├── actions
│   ├── (generic actions)
├── implementation
│   ├── (things that should go into implementation cnbs only)
├── language-family
│   ├── (things that should go into lang family cnbs only)
├── common
│   ├── (things that should go into both implementation & lang family cnbs)
│   ├── (this will have the dispatch receiver github workflow)
```

#### Sender workflow

There will be 3 sender workflows that will reside in `.github`.
It will be very similar to `implementation/workflows/send-dependency-update.yml` that makes use of `actions/dispatch`, except that:
```
on="push to implementation OR language-family OR common directories"
event="working-dir-update"
repo=<LIST OF TARGET REPOSITORIES> (this will be all impl cnbs for the workflow1, all lang cnbs for second workflow etc.)
 payload: |
          {
            "commit": <HEAD>,
            "pathmap": {
              "/implementaton": "/",
             }
          }
```
pathmap should be a mapping relative to the top-level directory of the Git working tree. It dictates how the updates in github-config should be mapped to the target repo. The above example is for the implementation cnb propagation workflow.

#### Receiver workflow

There will be 1 receiver workflow that will reside in `common`.
It will be very similar to `language-family/workflows/update-buildpack-toml.yml`.
It will, on receiving the dispatcher of type `working-dir-update`
clone github-config @ `payload.commit` and copy the directory contents with src
and dest dictated by `pathmap` and create a PR.

#### Auto-merging
There has to be `.mergify` config files in both `implementation` and `language-family` directories. (We could have put it in `common` but the conditions to merge are different)

They will take care of mergeing the PR generated in the above step and propagation of config files will be completed.

#### Blockers
* Add support to send dispatches to multiple targets in `action/dispatch`

cc @thitch97

**Comment by arjun024** [comment]
Looks like not much sense to have a `common` dir at that root. If there's some logic that's common to all, it should be an action and must be used by both implementation and family workflows

**Comment by ryanmoran** [comment]
@arjun024 @thitch97 are there pieces remaining to be done before we can close this?

**Comment by thitch97** [comment]
@ryanmoran Not as far as I can tell. Closing it out.
