### ISSUE TITLE
Publish Jammy stacks to GCR.io as well as dockerhub

### ISSUE THREAD

**Issue by robdimsdale** [paketo-buildpacks/github-config#602]
## Describe the Enhancement

We should publish the jammy stacks to GCR as well as dockerhub. Originally we didn't do this because we wanted to minimize expenditure, though that effort has been reevaluated and we would like to see jammy stack images in GCR, just like the Bionic images are.

**Comment by fg-j** [comment]
Was this discussed in a Working Group meeting? Just trying to gather some context on the decision.

**Comment by robdimsdale** [comment]
Sorry, it came from the buildpacks slack: https://cloud-native.slack.com/archives/C033DV8D9FB/p1666818920214199
