### ISSUE TITLE
Use prebuilt docker images for stacks actions

### ISSUE THREAD

**Issue by robdimsdale** [paketo-buildpacks/github-config#625]
## Problem statement

It appears that currently the most common cause of stacks CI failures is a failure to build docker images used by actions. The full output of an example failure is below, but in summary it appears to be a network-based flake when trying to download packages onto the image. We know it's flakey because the same steps will fail intermittently without modification to the dockerfiles used by the actions.

<details>
<summary>Example output from failed attempt to build docker image</summary>

```
Build container for action use: '/home/runner/work/_actions/paketo-buildpacks/github-config/main/actions/release/find-asset/Dockerfile'.
  /usr/bin/docker build -t 8d5581:2d7700d024ce4b7386c7eb4560b81615 -f "/home/runner/work/_actions/paketo-buildpacks/github-config/main/actions/release/find-asset/Dockerfile" "/home/runner/work/_actions/paketo-buildpacks/github-config/main/actions/release/find-asset"
  Sending build context to Docker daemon  7.168kB
  
  Step 1/4 : FROM alpine
  latest: Pulling from library/alpine
  ca7dd9ec2225: Pulling fs layer
  ca7dd9ec2225: Verifying Checksum
  ca7dd9ec2225: Download complete
  ca7dd9ec2225: Pull complete
  Digest: sha256:b95359c2505145f16c6aa384f9cc74eeff78eb36d308ca4fd902eeeb0a0b161b
  Status: Downloaded newer image for alpine:latest
   ---> bfe296a52501
  Step 2/4 : RUN apk add     bash     curl     git     github-cli     jq   && rm -rf /var/cache/apk/*
   ---> Running in f7f5fad6815d
  fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
  ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.16/main: network error (check Internet connection and firewall)
  WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.16/main: No such file or directory
  fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
  ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.16/community: network error (check Internet connection and firewall)
  WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.16/community: No such file or directory
  ERROR: unable to select packages:
    bash (no such package):
      required by: world[bash]
    curl (no such package):
      required by: world[curl]
    git (no such package):
      required by: world[git]
    github-cli (no such package):
      required by: world[github-cli]
    jq (no such package):
      required by: world[jq]
  The command '/bin/sh -c apk add     bash     curl     git     github-cli     jq   && rm -rf /var/cache/apk/*' returned a non-zero code: 5
  Warning: Docker build failed with exit code 5, back off 8.27 seconds before retry.
  /usr/bin/docker build -t 8d5581:2d7700d024ce4b7386c7eb4560b81615 -f "/home/runner/work/_actions/paketo-buildpacks/github-config/main/actions/release/find-asset/Dockerfile" "/home/runner/work/_actions/paketo-buildpacks/github-config/main/actions/release/find-asset"
  Sending build context to Docker daemon  7.168kB
  
  Step 1/4 : FROM alpine
   ---> bfe296a52501
  Step 2/4 : RUN apk add     bash     curl     git     github-cli     jq   && rm -rf /var/cache/apk/*
   ---> Running in 5e92333feaec
  fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
  fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
  ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.16/main: network error (check Internet connection and firewall)
  WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.16/main: No such file or directory
  ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.16/community: network error (check Internet connection and firewall)
  WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.16/community: No such file or directory
  ERROR: unable to select packages:
    bash (no such package):
      required by: world[bash]
    curl (no such package):
      required by: world[curl]
    git (no such package):
      required by: world[git]
    github-cli (no such package):
      required by: world[github-cli]
    jq (no such package):
      required by: world[jq]
  The command '/bin/sh -c apk add     bash     curl     git     github-cli     jq   && rm -rf /var/cache/apk/*' returned a non-zero code: 5
  Warning: Docker build failed with exit code 5, back off 7.292 seconds before retry.
  /usr/bin/docker build -t 8d5581:2d7700d024ce4b7386c7eb4560b81615 -f "/home/runner/work/_actions/paketo-buildpacks/github-config/main/actions/release/find-asset/Dockerfile" "/home/runner/work/_actions/paketo-buildpacks/github-config/main/actions/release/find-asset"
  Sending build context to Docker daemon  7.168kB
  
  Step 1/4 : FROM alpine
   ---> bfe296a52501
  Step 2/4 : RUN apk add     bash     curl     git     github-cli     jq   && rm -rf /var/cache/apk/*
   ---> Running in cd7ce404a73a
  fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
  fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
  ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.16/main: network error (check Internet connection and firewall)
  WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.16/main: No such file or directory
  ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.16/community: network error (check Internet connection and firewall)
  WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.16/community: No such file or directory
  ERROR: unable to select packages:
    bash (no such package):
      required by: world[bash]
    curl (no such package):
      required by: world[curl]
    git (no such package):
      required by: world[git]
    github-cli (no such package):
      required by: world[github-cli]
    jq (no such package):
      required by: world[jq]
  The command '/bin/sh -c apk add     bash     curl     git     github-cli     jq   && rm -rf /var/cache/apk/*' returned a non-zero code: 5
Error: Docker build failed with exit code 5
```
</details>

## Proposal

We can eliminate this class of failures entirely by doing the following:
1. pre-building the images for actions
1. pushing them to a registry (e.g. dockerhub)
1. referencing those pushed images in the `action.yml` file.

Concretely, we would change the `action.yml` from this:

```
runs:
  using: 'docker'
  image: 'Dockerfile'
```

to this:

```
runs:
  using: 'docker'
  image: 'docker://paketobuildpacks/some-image:some-tag'
```

For simplicity, I would propose that we manually build and push the images used by stacks, and use the `latest` tag. I am open to programmatically rebuilding and pushing the images, as well as using incrementing tags. It just seems like a lot more work for limited benefit.

As a side effect, switching to tags would also have a performance benefit as using a pre-built, cached, image is faster than building one every time. Empirically, we have observed that this benefit is minimal, as we tend to use small images that are quick to build and pull. Most of our images take less than 30 seconds to build and a similar amount of time to pull.

## Downsides

Using a cached image means that we will be using outdated packages/libraries.

Given that these docker images are only used to perform simple actions like finding and retrieving assets from GitHub releases, and they are only used for a short time in CI, I think the risk to security is minimal. We are unlikely to require features from newer packages for such simple tasks as we use in our CI, but we can always rebuild and push the images if necessary. We could also rebuild and push on a schedule if we wanted to ensure our images were up to date.

## Alternatives

1. We could publish the actions, but that requires moving each action to its own repo which is a significant change from our current architecture and would incur significant overhead.
1. We could explore whether switching away from `alpine` would improve reliability. However, without a more in-depth investigation, we can't say whether the issue is `alpine` specifically or if it is something common to other distributions (e.g. a networking issue within GitHub).

See also the (failed) exploration in #624

**Comment by sophiewigmore** [comment]
@robdimsdale this would probably work. What's your thought for how we'll manage publishing update images? Start manually and eventually automate?

**Comment by robdimsdale** [comment]
Yeah. There aren't too many images that we need to do this for (list below), so I'd propose creating and pushing each one manually. Nothing on those images makes its way into a product we ship, so I'm not super concerned about them being stale. But if we aren't comfortable with that, I'd propose we set up some automation to build and push the images (e.g. once per week, maybe once per day?).

Honestly, we could even rebuild and push the images at the same rate they are currently being built (i.e. every ten mins). The key thing that separates this from the current situation is the ability to add retry logic if we fail to build the image, and the fact that the building is decoupled from the consuming build. The issue is that we can't force GitHub to retry when it fails to build an image.

All the images used in create-release workflow:

* release/find-and-download-asset (actually composite of find-asset and download-asset)
* stack/generate-package-list
* stack/get-usns
* stack/create-stack
* stack/diff-package-receipts
* tag/increment-tag
* stack/release-notes
* release/create
* issue/file

The most important ones are the ones that run on schedule:

* release/find-asset
* release/download-asset
* stack/generate-package-list
* stack/get-usns

The rest of the images only get invoked when there is a change to the stack files, packages, or a manual trigger, so they run much less frequently. Therefore I am happy to not pre-build and push the images for the rest of the actions.

**Comment by sophiewigmore** [comment]
This makes sense to me, although I definitely don't think we need to rebuild the images every 10 minutes or even as close to as often as we run the workflow. I am in agreement about not being worried about the images becoming "stale". Let's start with the minimal set of scheduled actions that you posted and see how that goes?

**Comment by robdimsdale** [comment]
Great. I think the last outstanding question is where to push the images to / what naming scheme to use.

I'd like to leverage the existing `paketobuildpacks` DockerHub account, and I'd propose using a naming scheme like:

`ci-path-to-action`

e.g. for `stack/get-usns` that would look like:

`paketobuildpacks/ci-stack-get-usns`.

@paketo-buildpacks/tooling-maintainers any objections to pushing CI images to the existing `paketobuildpacks` DockerHub account with the above naming scheme?

**Comment by ryanmoran** [comment]
I think we should publish these to the GitHub Container Registry. The Java team has already been doing this for a while. You can see their images here: https://github.com/orgs/paketo-buildpacks/packages

**Comment by robdimsdale** [comment]
Ah, I didn't know that existed! Using GitHub Container Registry seems better because:
1. It avoids polluting the `paketobuildpacks` namespace on DockerHub (and avoids us having to create a second account)
2. I'd guess it might be slightly more performant, being integrated with Github.

@ryanmoran do you agree with my proposed naming scheme?

**Comment by ryanmoran** [comment]
I can't find it in their docs, but GHCR supported arbitrarily deeply nested image names with `/`s. I found this HN comment from a purported "Engineer on the GitHub Container Registry": https://news.ycombinator.com/item?id=24346600.

Given that, I think we could name the images something like `ghcr.io/paketo-buildpacks/actions/stacks/get-usns:latest`.

**Comment by robdimsdale** [comment]
If that works I think that's better. I'll explore that option, and fall back to `ghcr.io/paketo-buildpacks/actions-stacks-get-usns:latest` if it doesn't work as described.
