### ISSUE TITLE
Use `arm64` based tools when building stacks on `arm64` architecture

### ISSUE THREAD

**Issue by maliksalman** [paketo-buildpacks/github-config#756]
Currently, the tools that are used by various dependent stack projects assume `amd64` architecture even on `arm64` machines. These tools don't work on all `arm64` machines so we should use architecture specific versions of these tools.

## Possible Solution
All the tools scripts (`tools.sh`) that are used by stack, builder, and buildpack projects can detect when they are running on an `arm64` architecture using the `uname -m` command. If running on `arm64`, the tools these scripts download/install should then be the `arm64` versions since the `arm64` versions of these tools are now available. `jam` was the last holdout, but since [`2.1.1`](https://github.com/paketo-buildpacks/jam/releases/tag/v2.1.1) version that is not the case.

In addition, the stack create script (`stack/scripts/create.sh`) can use the same architecture detection mechanism and use architecture specific `jam` command passing in an architecture specific TOML filename. This is necessary since the TOML file contains architecture specific values. When creating the stack on `arm64`, we can possible rely on a file named `stack-arm64.toml` to keep it separate from `stack.toml` which is used to build `amd64` architecture images for backwards compatibility.

## Possible Side Effects
The stack project will now have to maintain multiple TOML files, one for each architecture. There would be bunch of common content between these TOML files but there would be enough differences to warrant a separate file for each architecture. For example, the Ubuntu Jammy APT repositories are completely different for different architectures. In some cases, the TOML files might need to specify architecture specific APT packages as well.

Another side effect of this change would be that stack artifacts (OCI image archives) produced will always match the architecture they were built on due to the auto-detection of architecture in the *create* script. This means that simply running `scripts/create.sh` on a dependent project (like on [`paketo-buildpacks/jammy-tiny-stack`](https://github.com/paketo-buildpacks/jammy-tiny-stack)) on an `arm64` machine, the resulting image archives would always produce `arm64` versions.

## Motivation
The `amd64` version tools probably work OK on Apple M1 Macs due to Rosetta2 translation layer but won't work on other `arm64` machines. All these changes should be backwards compatible and won't effect building `amd64` stack image archives on an `amd64` machine but would be helpful for the brave amongst us trying to build `arm64` artifacts on `arm64` machines.

**I can submit a PR to get us started on this**

**Comment by sophiewigmore** [comment]
Hey @maliksalman thanks for the details on this, we're glad for the support pushing forward ARM64 work! 

We will definitely need to make some modifications to our various workflows and scripts to accommodate multi-arch builds, but I am a little bit confused about the ask here. 

For stack creation specifically, I imagined that we could use a single `stack.toml` with platform-specific arguments as added in https://github.com/paketo-buildpacks/jam/pull/211. In the workflows we run to create the stacks via `scripts/create.sh`, we have the ability to spit out multi-arch stack images. From a project automation perspective, I think things would work as-is for stacks unless I'm missing something. 

Is your use-case for utilising these scripts and tools locally on your M1?

**Comment by robdimsdale** [comment]
I'm also a little confused about the scope of the ask.

I think I see a couple of levels to this request:

1. the scripts used to build a stack (e.g. [`tools.sh`](https://github.com/paketo-buildpacks/github-config/blob/main/stack/scripts/.util/tools.sh)) should download tools that are specific to the architecture rather than relying on the fact that the host operating system might be able to do instruction translation from x86_64 (e.g. Rosetta on Mac OS).
    * **Sounds good - feel free to submit a PR**
2. Automatically setting the stack platform to match the host when running the create script (and making stack-specific `stack.toml` files).
    * **I'm not sure about this**.
    * It seems better for the Paketo stacks to be built for all supported architectures, and those architectures encoded in the `stack.toml`. I think we would want to add `arm64` as a supported platform to all stacks' `stack.toml` files.
    * For custom stacks that make use of this automation, they can have whatever supported architectures they wish in their `stack.toml` files.
    * I'm a bit confused about your comment that the apt repositories would be different for amd64 vs arm64. It's been a while since I built a stack for multiple architectures, but my memory was that it worked just fine. If the URLs were different I would have expected a failure during stack creation.
    * I don't expect the paketo stacks to have architecture-specific dependencies, so I don't think we need to make stack specific `stack.toml` files for the Paketo stacks. It's possible that I'm missing something here, as we haven't tried building all stacks (full/base/tiny/static) for the arm architecture.

It would be really helpful if you could show us a concrete example of how the Paketo stacks fail when attempting build multi-arch images (after manually adding `arm64` to the `platforms` in `stack.toml`).

To be clear, I'm open to the idea of arch-specific `stack.toml` if we prove the need for it - I just haven't seen the requirement come up yet. You may be the first to encounter it 😄

**Comment by maliksalman** [comment]
Sorry, was on vacation last week and didn't get a chance to respond. 

@sophiewigmore, the use case is to be able to make it easier to create stacks/builders and run workloads on `arm64` hardware with *buildpacks* that are as close to their `amd64` counterparts as possible - other than Apple M1.

@robdimsdale, agreed this is two requests in one. I can create two separate PRs with the `tools.sh` changes going in first to use platform specific binaries.

On the 2nd point though, even though I agree that we can specify multiple platforms in `stack.toml` file, there are other values that need to be platform specific. I do think we would need separate `stack.toml` files, one for each platform. For example:

- Trying to run `apt update` on an `arm64` machine while your `/etc/apt/sources.list` points to 

```
deb http://archive.ubuntu.com/ubuntu jammy main universe multiverse
deb http://archive.ubuntu.com/ubuntu jammy-updates main universe multiverse
deb http://archive.ubuntu.com/ubuntu jammy-security main universe multiverse
```

will result in errors, with subsequent `apt` commands no longer functional. On `arm64`, the contents of that file need to be:

```
deb http://ports.ubuntu.com/ubuntu-ports jammy main universe multiverse
deb http://ports.ubuntu.com/ubuntu-ports jammy-updates main universe multiverse
deb http://ports.ubuntu.com/ubuntu-ports jammy-security main universe multiverse
```

- Also, if you look at https://github.com/paketo-buildpacks/jammy-full-stack/blob/main/stack/stack.toml - you'll see mentions of a lot of `amd64` packages. When building an `arm64` version of this stack, those packages would not be appropriate.

**Comment by robdimsdale** [comment]
No worries @maliksalman .

Did you see this PR: https://github.com/paketo-buildpacks/jammy-tiny-stack/pull/108

It demonstrates how you would get architecture-specific configuration within a single `stack.toml` file. In short, you can override build/run arguments within a single `stack.toml`, which is primarily useful for the exact issue you're describing.

This was the mechanism I was thinking of above, but I couldn't find an example of how it works. I think this gives us all the tools we need to separate out architectures within a single `stack.toml` file. You should be able to either build all architectures for the stack via the single `stack.toml`, and if that didn't work you could fall back to modifing the `stack.toml` to only have a single architecture that you are able to build. If you agree with this, then do you also agree that we don't need to have separate handling for architecture within the script?

**Comment by maliksalman** [comment]
@robdimsdale, @sophiewigmore, thanks for pointing me to the [paketo-buildpacks/jam#211](https://github.com/paketo-buildpacks/jam/pull/211) *jam* capability and the example in the PR mentioned above. This totally removes the need for architecture specific `stack.toml` files. I had somehow missed that.

I still think that architecture specific tools are needed in the various `tools.sh` scripts. This is in cases where these scripts are run on non Apple `arm64` machines.

**Comment by robdimsdale** [comment]
> I still think that architecture specific tools are needed in the various tools.sh scripts. This is in cases where these scripts are run on non Apple arm64 machines.

To make sure we're on the same page - this is the idea that the scripts that download `jam`, `pack`, `jq`, etc need to download platform-specific binaries?

**Comment by maliksalman** [comment]
> To make sure we're on the same page - this is the idea that the scripts that download jam, pack, jq, etc need to download platform-specific binaries?

Yes. Currently, the scripts explicitly downloads `amd64` binaries.

**Comment by robdimsdale** [comment]
Great. I would wholeheartedly welcome a PR to the scripts that download architecture-specific tools. You can constrain it to the stacks if that's all you care about, but at some point we'd want to do this for buildpacks too so there's no harm in you making that change all over this repo.

**Comment by maliksalman** [comment]
I will submit a PR shortly. For completeness, I am going to make the change to all `tools.sh` scripts and not just for stacks.
